### ISSUE TITLE
No windows deployment guide

### ISSUE THREAD

**Issue by heyanctil** [ozone-development/ozp-documentation#10]
I know that it is not really an issue but it is the only way I've found to ask you about OZP supporting Windows. We've build our stack on Windows and using OWF 7.16 and we're looking to move to OZP. But there is no guide for Windows. Is it something you will address soon?

**Comment by tonyalletag** [comment]
The OZP development team is focused on free and open source deployments and is not planning to provide documentation or support for Windows. A request for new features can be made by creating a new issue here https://github.com/ozone-development/ozp-community-request
