### ISSUE TITLE
Ending of legacy support

### ISSUE THREAD

**Issue by danhooper** [ozone-development/ozp-documentation#13]
The roadmap image shows the ending of legacy support in Apr 18 2016.  Does this refer to OZP's backwards compatibility with OWF or does this mean OWF itself is no longer supported?

**Comment by tonyalletag** [comment]
The OZP development team not update the legacy adapter or fix bugs after Apr 18 2016 and backward compatibility decommissioned in our production environment.  OWF has limited resources at this time however there is the possibility that a custodian of OWF will continue to support the project.

**Comment by danhooper** [comment]
Thanks!
